import { SignUp } from "@clerk/nextjs";

export const metadata = {
  title: "Sign up | QRmory",
  description: "Generated by Next.js",
};

export default function SignInPage() {
  return (
    <main>
      <SignUp />
    </main>
  );
}
