import { SignIn } from "@clerk/nextjs";

export const metadata = {
  title: "Log in | QRmory",
  description: "Generated by Next.js",
};

export default function SignInPage() {
  return (
    <main>
      <SignIn />
    </main>
  );
}
