import SignIn from "@/components/SignIn";

export const metadata = {
  title: "Log in | QRmory",
  description: "Generated by Next.js",
};

export default function SignInPage() {
  return <SignIn />;
}
