import AuthText from "@/components/AuthText";
import Link from "next/link";
import SignUp from "@/components/SignUp";

export const metadata = {
  title: "Sign up | QRmory",
  description: "Generated by Next.js",
};

export default function SignUpPage() {
  return <SignUp />;
}
